version: '3.8'

services:
 db-test:
  image: postgres:15-alpine
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: dbName
  ports:
   - "5433:5432"
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres -d dbName"]
    interval: 5s
    timeout: 5s
    retries: 5
  networks:
    - test_network

 migrate-test:
  image: migrate/migrate
  depends_on:
   db-test:
    condition: service_healthy
  volumes:
    - ./user_service/migration:/migrations
  command:
    - "-path"
    - "/migrations"
    - "-database"
    - "postgres://postgres:postgres@db-test:5432/dbName?sslmode=disable"
    - "up"
  restart: "no"
  networks:
    - test_network

networks:
  test_network:
    driver: bridge