// Code generated by MockGen. DO NOT EDIT.
// Source: dto.go

// Package mockschat is a generated GoMock package.
package mocks

import (
	domain "chat_service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProducerEvents is a mock of ProducerEvents interface.
type MockProducerEvents struct {
	ctrl     *gomock.Controller
	recorder *MockProducerEventsMockRecorder
}

// MockProducerEventsMockRecorder is the mock recorder for MockProducerEvents.
type MockProducerEventsMockRecorder struct {
	mock *MockProducerEvents
}

// NewMockProducerEvents creates a new mock instance.
func NewMockProducerEvents(ctrl *gomock.Controller) *MockProducerEvents {
	mock := &MockProducerEvents{ctrl: ctrl}
	mock.recorder = &MockProducerEventsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerEvents) EXPECT() *MockProducerEventsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockProducerEvents) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProducerEventsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProducerEvents)(nil).Close))
}

// SendDeleteMessageEvent mocks base method.
func (m *MockProducerEvents) SendDeleteMessageEvent(ctx context.Context, userID, message int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDeleteMessageEvent", ctx, userID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDeleteMessageEvent indicates an expected call of SendDeleteMessageEvent.
func (mr *MockProducerEventsMockRecorder) SendDeleteMessageEvent(ctx, userID, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDeleteMessageEvent", reflect.TypeOf((*MockProducerEvents)(nil).SendDeleteMessageEvent), ctx, userID, message)
}

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockMessageRepository) DeleteMessage(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageRepositoryMockRecorder) DeleteMessage(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageRepository)(nil).DeleteMessage), id)
}

// MessageHistory mocks base method.
func (m *MockMessageRepository) MessageHistory(limit, offset int64) ([]domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageHistory", limit, offset)
	ret0, _ := ret[0].([]domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageHistory indicates an expected call of MessageHistory.
func (mr *MockMessageRepositoryMockRecorder) MessageHistory(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageHistory", reflect.TypeOf((*MockMessageRepository)(nil).MessageHistory), limit, offset)
}

// SaveMessage mocks base method.
func (m *MockMessageRepository) SaveMessage(msg domain.Message) (domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", msg)
	ret0, _ := ret[0].(domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessageRepositoryMockRecorder) SaveMessage(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessageRepository)(nil).SaveMessage), msg)
}

// MockTokenManager is a mock of TokenManager interface.
type MockTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockTokenManagerMockRecorder
}

// MockTokenManagerMockRecorder is the mock recorder for MockTokenManager.
type MockTokenManagerMockRecorder struct {
	mock *MockTokenManager
}

// NewMockTokenManager creates a new mock instance.
func NewMockTokenManager(ctrl *gomock.Controller) *MockTokenManager {
	mock := &MockTokenManager{ctrl: ctrl}
	mock.recorder = &MockTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenManager) EXPECT() *MockTokenManagerMockRecorder {
	return m.recorder
}

// VerifyToken mocks base method.
func (m *MockTokenManager) VerifyToken(token string) (int64, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", token)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockTokenManagerMockRecorder) VerifyToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockTokenManager)(nil).VerifyToken), token)
}
